import type { NursingSummaryRecord } from "../nursingChart";

export const PATIENT_A_NURSING_SUMMARIES: NursingSummaryRecord[] = [
  {
    id: "nsum-a-admission",
    period: "2021/06/18 〜 入院直後",
    date: "2021/06/19",
    author: "田中 花子",
    title: "入院時看護サマリー",
    living: "医療保護入院。表情硬く被害的訴えあり。セルフケアは促しを要する。",
    symptoms: "幻覚妄想の増悪。緊張強い。",
    sleep: "入眠困難。幻聴の影響が疑われる。",
    medication: "看護管理下で服薬開始。",
    adl: "食事・保清・整容は促しを要する。",
    activity: "病室中心。集団は苦手。",
    interpersonal: "周囲への関心は乏しい。",
    physical: "身長165cm、体重約80kg。",
    ongoingIssues: "安全確保、生活リズムの再構築、安心できる関係づくり。",
    strengths: "会話は可能。訴えを言語化できる。",
  },
  {
    id: "nsum-a-mid-2022",
    period: "2022/01 〜 2022/12",
    date: "2022/12/20",
    author: "田中 花子",
    title: "中間看護サマリー",
    living: "病棟生活は概ね安定。生活リズムは保たれつつある。",
    symptoms: "被害的訴えは減少。幻聴は夜間に残存。",
    sleep: "入眠困難が散発。ラジオで対処する場面あり。",
    medication: "看護管理で確実。飲み忘れなし。",
    adl: "入浴・洗濯は促しで実施。口腔ケアは声かけを要する。",
    activity: "日中は室内が多い。OT参加は不安定。",
    interpersonal: "同室者との関わりは限定的。",
    physical: "体重やや増加（約79kg）。脂質管理の必要性あり。",
    ongoingIssues: "日中活動の低下、体重・脂質管理。",
    strengths: "服薬遵守。便秘を自ら訴えられる。",
  },
  {
    id: "nsum-a-voluntary",
    period: "2023/07/10 任意入院移行時",
    date: "2023/07/10",
    author: "田中 花子",
    title: "任意入院移行時看護サマリー",
    living: "任意入院へ移行。病棟生活は継続。",
    symptoms: "症状は安定。日中は穏やか。",
    sleep: "夜間の幻聴・不眠は継続。頓用使用あり。",
    medication: "看護管理継続。自己管理への関心は乏しい。",
    adl: "促しでセルフケアは維持。",
    activity: "SSTには時々参加。OT辞退が多い。",
    interpersonal: "Iさんとの関わりが増え始める。",
    physical: "体重はやや高値。",
    ongoingIssues: "退院先未定。地域生活への不安。",
    strengths: "安定した病棟生活。SST参加の芽。",
  },
  {
    id: "nsum-a-lastyear",
    period: "2024/01 〜 2024/12",
    date: "2024/12/25",
    author: "田中 花子",
    title: "前年度看護サマリー",
    living: "概ね安定。生活リズムは保たれる。",
    symptoms: "残遺幻聴は夜間中心。急性増悪なし。",
    sleep: "入眠困難・頓用使用が散発。翌朝の眠気に留意。",
    medication: "看護管理で確実。Iさんの自己管理に関心が芽生える。",
    adl: "促しで保清維持。洗濯のため込みあり。",
    activity: "OT辞退多い。SST参加は定着傾向。",
    interpersonal: "Iさんと中庭で過ごす場面あり。叔父の面会減少に不安。",
    physical: "間食制限に取り組み始め。体重やや高値。",
    ongoingIssues: "日中活動、服薬自己管理、体重管理、退院支援。",
    strengths: "便秘・体調の自己訴え。SST参加の定着。",
  },
  {
    id: "nsum-a-current",
    period: "2025/01 〜 現在",
    date: "2025/07/01",
    author: "田中 花子",
    title: "現在看護サマリー",
    living: "病棟生活は安定。任意入院継続。",
    symptoms: "残遺幻聴（夜間）。感冒は一時的に発症し軽快。",
    sleep: "ラジオでの対処、頓用使用あり。翌朝の倦怠感に留意。",
    medication: "看護管理で確実。自己管理への関心と不安が併存。",
    adl: "入浴・洗濯・口腔ケアは促しで維持。",
    activity: "SST参加定着。OTは気が向かず辞退する日が多い。",
    interpersonal: "Iさんとの交流が安心の資源。叔父の話題で沈む場面あり。",
    physical: "体重約70kgまで減少。脂質改善傾向。",
    ongoingIssues: "服薬・金銭の自己管理、日中活動、退院・地域生活。",
    strengths: "体重管理の継続、SST参加、Iさんとの関係、体調の自己報告。",
  },
  {
    id: "nsum-a-conference",
    period: "2025/07/01 〜 2025/07/07（カンファレンス前）",
    date: "2025/07/06",
    author: "田中 花子",
    title: "カンファレンス前看護サマリー",
    living: "病棟生活安定。感冒は軽快傾向。",
    symptoms: "幻聴は夜間に残存。行動化なし。",
    sleep: "前夜頓用使用あり。翌朝の起床遅延に注意。",
    medication: "定期・頓服とも遵守。自己管理は段階的検討中。",
    adl: "促しでセルフケア維持。",
    activity: "SST継続。OT辞退あり。",
    interpersonal: "Iさんと中庭で過ごす場面。",
    physical: "体重70.2kg。間食ルール継続。",
    ongoingIssues: "睡眠・頓用、自己管理、退院支援。",
    strengths: "SST・体重管理・Iさんとの関係。",
  },
];
