import type { NursingPlanItem } from "../nursingChart";

export const PATIENT_A_NURSING_PLAN: NursingPlanItem[] = [
  {
    problemNumber: "N1",
    problem: "夜間の幻聴と睡眠の乱れ",
    longTermGoal: "残遺する幻聴があっても、生活リズムを保ち入眠できる。",
    shortTermGoal: "頓用薬を適切に使用し、翌朝の状態を自己報告できる。",
    op: "夜間の観察、入眠・中途覚醒・起床の記録、頓用使用と効果の確認。",
    tp: "ラジオ等の対処を支持。不眠時頓服の適切な使用を説明。翌朝の眠気・倦怠感を聞き取る。",
    ep: "幻聴と不眠の関連、頓用の効果と翌朝への影響を評価。",
    startDate: "2021/06/19",
    reviewDate: "2025/07/01",
    status: "継続",
  },
  {
    problemNumber: "N2",
    problem: "服薬自己管理への不安",
    longTermGoal: "服薬の必要性を理解し、段階的に自己管理へ移行できる。",
    shortTermGoal: "Iさんの自己管理を観察し、関心を言語化できる。",
    op: "服薬状況の確認、自己管理への関心・不安の聞き取り。",
    tp: "関心を受け止め、薬剤師・医師と情報共有。即時の自己管理移行は行わない。",
    ep: "関心の芽と不安のバランスを評価。",
    startDate: "2024/10/01",
    reviewDate: "2025/07/01",
    status: "継続",
  },
  {
    problemNumber: "N3",
    problem: "日中活動性の低下",
    longTermGoal: "本人のペースで日中活動を維持できる。",
    shortTermGoal: "SST等、参加できる活動を週数回継続する。",
    op: "OT・SST参加状況、日中の活動量の観察。",
    tp: "辞退を尊重しつつ、関心のある活動を確認。参加できた点を伝える。",
    ep: "活動量と参加体験を評価。",
    startDate: "2021/06/19",
    reviewDate: "2025/07/01",
    status: "継続",
  },
  {
    problemNumber: "N4",
    problem: "便秘傾向",
    longTermGoal: "排便リズムを保ち、不快感なく過ごせる。",
    shortTermGoal: "3〜5日間隔を自己報告し、必要時に頓用を使用できる。",
    op: "排便間隔・腹部症状の観察。",
    tp: "水分・活動を促す。頓用センノシドの使用を確認。",
    ep: "頓用の効果と腹部所見を評価。",
    startDate: "2021/06/19",
    reviewDate: "2025/07/01",
    status: "継続",
  },
  {
    problemNumber: "N5",
    problem: "体重・栄養管理",
    longTermGoal: "適正体重を維持し、脂質異常の再発を防ぐ。",
    shortTermGoal: "間食一つ・非甘味飲料のルールを継続する。",
    op: "体重・食事・間食の観察。",
    tp: "取り組みを肯定。栄養指導と連携。",
    ep: "体重推移と食習慣を評価。",
    startDate: "2022/12/01",
    reviewDate: "2025/07/01",
    status: "継続",
  },
  {
    problemNumber: "N6",
    problem: "地域生活への不安",
    longTermGoal: "退院後の生活イメージを段階的に持てる。",
    shortTermGoal: "「ここにいる方が安心」という気持ちを傾聴し、焦らず支援を受けられる。",
    op: "退院・地域生活に関する発言の聞き取り。",
    tp: "PSWと連携。本人のペースを尊重。",
    ep: "不安の背景と支援の受け入れを評価。",
    startDate: "2023/07/10",
    reviewDate: "2025/07/01",
    status: "継続",
  },
];
